# Site settings
title: Developers Group
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Um blog cooperativo, criado pelos integrantes de um grupo de amigos desenvolvedores com intuito
  contínuo de absorver e compartilhar conhecimento.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: DevsGroup
github_username:  DevsGroup

# Build settings
markdown: kramdown
permalink: /:title/


# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
